# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='Creation time')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='Finish time')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
